# Generated by Django 4.1.7 on 2023-04-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0002_remove_list_cards_list_board_list_name"),
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="list",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="list.list"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="card",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
