# Generated by Django 4.1.7 on 2023-04-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cards",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="card.card"
                    ),
                ),
            ],
        ),
    ]
