# Generated by Django 4.1.7 on 2023-04-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_remove_board_lists_board_name"),
        ("list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="list",
            name="cards",
        ),
        migrations.AddField(
            model_name="list",
            name="board",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="board.board"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="list",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
