# Generated by Django 4.1.7 on 2023-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="lists",
        ),
        migrations.AddField(
            model_name="board",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
